// All the data in a big array, individual answers should be [ "Answer", year, "optional trivia (unused so far)" ]
module.exports = [
  [
    'Best picture',
    [
      [ "King's Speech", 2010 ],
      [ "Hurt Locker", 2009 ],
      [ "Slumdog Millionaire", 2008 ],
      [ "No Country For Old Men", 2007 ],
      [ "The Departed", 2006 ],
      [ "Crash", 2005 ],
      [ "Million Dollar Baby", 2004 ],
      [ "Lord of the Rings: ROTK", 2003 ],
      [ "Chicago", 2002 ],
      [ "A Beautiful Mind", 2001 ],
      [ "Gladiator", 2000 ],
      [ "American Beauty", 1999 ],
      [ "Shakespeare in Love", 1998 ],
      [ "Titanic", 1997 ],
      [ "English Patient", 1996 ],
      [ "Braveheart", 1995 ],
      [ "Forrest Gump", 1994 ],
      [ "Schindler's List", 1993 ],
      [ "Unforgiven", 1992 ],
      [ "Silence of the Lambs", 1991 ],
      [ "Dances with Wolves", 1990 ],
      [ "Driving Miss Daisy", 1989 ],
      [ "Rain Man", 1988 ],
      [ "The Last Emperor", 1987 ],
      [ "Platoon", 1986 ],
      [ "Out of Africa", 1985 ],
      [ "Amadeus", 1984 ],
      [ "Terms of Endearment", 1983 ],
      [ "Ghandi", 1982 ],
      [ "Chariots of Fire", 1981 ],
      [ "Ordinary People", 1980 ],
      [ "Kramer Vs Kramer", 1979 ],
      [ "The Deer Hunter", 1978 ],
      [ "Annie Hall", 1977 ],
      [ "Rocky", 1976 ],
      [ "One Flew Over the Cuckoo's Nest", 1975 ],
      [ "The Godfather Part II", 1974 ],
      [ "The Sting", 1973 ],
      [ "The Godfather", 1972 ],
      [ "The French Connection", 1971 ],
      [ "Patton", 1970 ]
    ],
    'Only gone back to 1970 so far, Clare to add more here...'
  ],
  [
    'Best actor',
    [
      [ "Colin Firth", 2010, "King's Speech" ],
      [ "Jeff Bridges", 2009, "Crazy Heart" ],
      [ "Sean Penn", 2008, "Milk" ],
      [ 'Daniel Day-Lewis', 2007, '(There Will Be Blood)' ],
      [ 'Forrest Whitaker', 2006, '(Last King of Sctoland)' ],
      [ 'Phillip Seymour-Hoffman', 2005, '(Capote)' ],
      [ 'Jamie Foxx', 2004, '(Ray)' ],
      [ 'Sean Penn', 2003, '(Mystic River)' ],
      [ 'Adrian Brody', 2002, '(The Pianist)' ],
      [ 'Denzel Washington', 2001, '(Training Day)' ],
      [ 'Russell Crowe', 2000, '(Gladiator)' ],
      [ 'Kevin Spacey', 1999, '(American Beauty)' ],
      [ 'Roberto Benigni', 1998, '(Life is Beautiful)' ],
      [ 'Jack Nicholson', 1997, '(As Good as it Gets)' ],
      [ 'Geoffrey Rush', 1996, '(Shine)' ],
      [ 'Nicholas Cage', 1995, '(Leaving Las Vegas)' ],
      [ 'Tom Hanks', 1994, '(Forrest Gump)' ],
      [ 'Tom Hanks', 1993, '(Philadelphia)' ],
      [ 'Al Pacino', 1992, '(Scent of a Woman)' ],
      [ 'Anthony Hopkins', 1991, '(Silence of the Lambs)' ],
      [ 'Jeremy Irons', 1990, '(Reversal of Fortune)' ],
      [ 'Daniel Day Lewis', 1989, '(My Left Foot)' ],
      [ 'Dustin Hoffman', 1988, '(Rain Man)' ],
      [ 'Michael Douglas', 1987, '(Wall Street)' ],
      [ 'Paul Newman', 1986, '(The Colour of Money)' ],
      [ 'John Hurt', 1985, '(Kiss of the Spider Woman)' ],
      [ 'F. Murray Abraham', 1984, '(Amadeus)' ],
      [ 'Robert Duvall', 1983, '(Tender Mercies)' ],
      [ 'Ben Kingsley', 1982, '(Ghandi)' ],
      [ 'Henry Fonda', 1981, '(On Golden Pond)' ],
      [ 'Robert Di Nero', 1980, '(Raging Bull)' ],
      [ 'Dustin Hoffman', 1979, '(Kramer Vs Kramer)' ],
      [ 'Jon Voight', 1978, '(Coming Home)' ],
      [ 'Richard Dreyfuss', 1977, '(The Goodbye Girl)' ],
      [ 'Peter Finch', 1976, '(Network)' ],
      [ 'Jack Nicholson', 1975, "(One Flew Over the Cuckoo's Nest)" ],
      [ 'Art Cartney', 1974, '(Harry and Tonto)' ],
      [ 'Jack Lemmon', 1973, '(Save the Tiger)' ],
      [ 'Marlon Brando', 1972, '(The Godfather, declined)' ],
      [ 'Gene Hackman', 1971, '(The French Connection)' ],
      [ 'George C Scott', 1970, '(Patton, declined)' ]
    ],
    'Need to add more actors here I know, coming soon...'
  ],
  [
    'Best actress',
    [
      [ "Natalie Portman", 2010, "Black Swan" ],
      [ "Sandra Bullock", 2009, "The Blind Side" ],
      [ "Kate Winslet", 2008, "The Reader" ],
      [ "Marion Cotillard", 2007, "La Vie en Rose" ],
      [ "Helen Mirren", 2006, "The Queen" ],
      [ "Reese Witherspoon", 2005, "Walk the Line" ],
      [ "Hilary Swank", 2004, "Million Dollar Baby" ],
      [ "Charlize Theron", 2003, "Monster" ],
      [ "Nicole Kidman", 2002, "The Hours" ],
      [ "Halle Berry", 2001, "Monster's Ball" ],
      [ "Julia Roberts", 2000, "Erin Brockavitch" ],
      [ "Hilary Swank", 1999, "Boys Don't Cry" ],
      [ "Gwyneth Paltrow", 1998, "Shakespeare in Love" ],
      [ "Helen Hunt", 1997, "As Good as it Gets" ],
      [ "Frances McDormand", 1996, "Fargo" ],
      [ "Susan Sarandon", 1995, "Dead Man Walking" ],
      [ "Jessica Lange", 1994, "Blue Sky" ],
      [ "Holly Hunter", 1993, "The Piano" ],
      [ "Emma Thompson", 1992, "Howard's End" ],
      [ "Jodie Foster", 1991, "Silence of the Lambs" ],
      [ "Kathy Bates", 1990, "Misery" ],
      [ "Jessica Tandy", 1989, "Driving Miss Daisy" ],
      [ "Jodie Foster", 1988, "The Accused" ],
      [ "Cher", 1987, "Moonstruck" ],
      [ "Marlee Matlin", 1986, "Children of a Lesser God" ],
      [ "Geraldine Page", 1985, "Trip to Bountiful" ],
      [ "Sally Field", 1984, "Places in the Heart" ],
      [ "Shirley Maclaine", 1983, "Terms of Endearment" ],
      [ "Meryl Streep", 1982, "Sophie's Choice" ],
      [ "Katherine Hepburn", 1981, "On Golden Pond" ],
      [ "Cissy Spacek", 1980, "Coal Miner's Daughter" ],
      [ "Sally Field", 1979, "Norma Rae" ],
      [ "Jane Fonda", 1978, "Coming Home" ],
      [ "Diane Keaton", 1977, "Annie Hall" ],
      [ "Faye Dunaway", 1976, "Network" ],
      [ "Louise Fletcher", 1975, "One Flew Over the Cuckoo's Nest" ],
      [ "Ellen Burstyn", 1974, "Alice Doesn't Live Here Anymore" ],
      [ "Glenda Jackson", 1973, "A Touch of Class" ],
      [ "Liza Minelli", 1972, "Caberet" ],
      [ "Jane Fonda ", 1971, "Klute" ],
      [ "Glenda Jackson", 1970, "Women in Love" ]
    ],
    'Need to add more actresses here I know, coming soon...'
  ],
  [
    'BBC sports personality of the year',
    [
      [ "Ryan Giggs", 2009, "football" ],
      [ "Chris Hoy", 2008, "cycling" ],
      [ "Joe Calzaghe", 2007, "boxing" ],
      [ "Zara Phillips", 2006, "equestrian" ],
      [ "Andrew Flintoff", 2005, "cricket" ],
      [ "Kelly Holmes", 2004, "athletics" ],
      [ "Jonny Wilkinson", 2003, "rugby" ],
      [ "Paula Radcliffe", 2002, "athletics" ],
      [ "David Beckham", 2001, "football" ],
      [ "Steve Redgrave", 2000, "rowing" ],
      [ "Lennox Lewis", 1999, "boxing" ],
      [ "Michael Owen", 1998, "football" ],
      [ "Greg Rusedski", 1997, "tennis" ],
      [ "Damon Hill", 1996, "motor racing" ],
      [ "Jonathan Edwards", 1995, "athletics" ],
      [ "Damon Hill", 1994, "motor sport" ],
      [ "Linford Christie", 1993, "athletics" ],
      [ "Nigel Mansell", 1992, "motor racing" ],
      [ "Liz McColgan", 1991, "athletics" ],
      [ "Paul Gascoigne", 1990, "football" ],
      [ "Nick Faldo", 1989, "golf" ],
      [ "Steve Davis", 1988, "snooker" ],
      [ "Fatima Whitbread", 1987, "athletics" ],
      [ "Nigel Mansell", 1986, "motor racing" ],
      [ "Barry McGuigan", 1985, "boxing" ],
      [ "Jayne Torvill and Christopher Dean", 1984, "ice skating" ],
      [ "Steve Cram", 1983, "athletics" ],
      [ "Daley Thompson", 1982, "athletics" ],
      [ "Ian Botham", 1981, "cricket" ],
      [ "Robin Cousins", 1980, "ice skating" ],
      [ "Sebastian Coe", 1979, "athletics" ],
      [ "Steve Ovett", 1978, "athletics" ],
      [ "Virginia Wade", 1977, "tennis" ],
      [ "John Curry", 1976, "ice skating" ],
      [ "David Steele", 1975, "cricket" ],
      [ "Brendan Foster", 1974, "athletics" ],
      [ "Jackie Stewart", 1973, "motor racing" ],
      [ "Mary Peters", 1972, "athletics" ],
      [ "Princess Anne", 1971, "equestrian" ],
      [ "Henry Cooper", 1970, "boxing" ],
      [ "Ann Jones", 1969, "tennis" ],
      [ "David Hemery", 1968, "athletics" ],
      [ "Henry Cooper", 1967, "boxing" ],
      [ "Bobby Moore", 1966, "football" ],
      [ "Tommy Simpson", 1965, "cycling" ],
      [ "Mary Rand", 1964, "athletics" ],
      [ "Dorothy Hyman", 1963, "athletics" ],
      [ "Anita Lonsbrough", 1962, "swimming" ],
      [ "Stirling Moss", 1961, "motor racing" ],
      [ "David Broome", 1960, "showjumping" ],
      [ "John Surtees", 1959, "motor cycling" ],
      [ "Ian Black", 1958, "swimming" ],
      [ "Dai Rees", 1957, "golf" ],
      [ "Jim Laker", 1956, "cricket" ],
      [ "Gordon Pirie", 1955, "athletics" ],
      [ "Chris Chataway", 1954, "athletics" ]
    ],
    'Think I have all of these in now'
  ],
  [
    "UK and Ireland IATA codes",
    [
      [ "RAF Abingdon", "ABB" ],
      [ "Aberdeen Dyce", "ABZ" ],
      [ "Andover Airfield", "ADV" ],
      [ "RAF Leuchars", "ADX" ],
      [ "Bembridge", "BBP" ],
      [ "Blackbushe", "BBS" ],
      [ "Benbecula", "BEB" ],
      [ "RAF Honington", "BEQ" ],
      [ "RAF Benson", "BEX" ],
      [ "Belfast International", "BFS" ],
      [ "George Best Belfast City", "BHD" ],
      [ "Birmingham", "BHX" ],
      [ "Birmingham International", "BHX" ],
      [ "Blackpool International", "BLK" ],
      [ "Belmullet Aerodrome", "BLY" ],
      [ "Bournemouth", "BOH" ],
      [ "Ballykelly", "BOL" ],
      [ "London Biggin Hill", "BQH" ],
      [ "Barra", "BRR" ],
      [ "Barra", "BRR", '(the famous tidal beach landing)' ],
      [ "Bristol International", "BRS" ],
      [ "Barrow Walney Island", "BWF" ],
      [ "Bantry Aerodrome", "BYT" ],
      [ "RAF Brize Norton", "BZZ" ],
      [ "Campbeltown", "CAL" ],
      [ "Carlisle", "CAX" ],
      [ "Cambrigde", "CBG" ],
      [ "Hawarden", "CEG" ],
      [ "Donegal", "CFN", "(Carrickfin)" ],
      [ "Reeroe", "CHE" ],
      [ "Castlebar", "CLB" ],
      [ "Coll", "COL" ],
      [ "Colonsay Airstrip", "CSA" ],
      [ "Coventry - Baginton", "CVT" ],
      [ "Cardiff International", "CWL" ],
      [ "Sheffield, Doncaster, Robin Hood International", "DCS" ],
      [ "MOD St. Athan", "DGX" ],
      [ "Dundee", "DND" ],
      [ "Dornoch", "DOC" ],
      [ "Robin Hood Doncaster Sheffield", "DSA" ],
      [ "Dublin", "DUB" ],
      [ "Edinburgh", "EDI" ],
      [ "Nottingham - East Midlands", "EMA" ],
      [ "St Angelo", "ENK" ],
      [ "Eday", "EOI" ],
      [ "Shoreham", "ESH" ],
      [ "Elstree Airfield", "ETR" ],
      [ "Exeter International", "EXT" ],
      [ "Farnborough", "FAB" ],
      [ "RAF Fairford", "FFD" ],
      [ "Fair Isle (Shetland)", "FIE" ],
      [ "Flotta Isle", "FLH" ],
      [ "Foula (Shetland)", "FOU" ],
      [ "Fairoaks", "FRK" ],
      [ "RAF Kinloss", "FSS" ],
      [ "Bristol Filton", "FZO" ],
      [ "Glasgow International", "GLA" ],
      [ "Gloucestershire", "GLO" ],
      [ "Binbrook Airfield", "GSY" ],
      [ "Galway", "GWY" ],
      [ "Haverfordwest", "HAW" ],
      [ "Anglesey", "HLY" ],
      [ "RAF Linton-On-Ouse", "HRT" ],
      [ "Humberside", "HUY" ],
      [ "Inishmaan Aerodrome", "IIA" ],
      [ "Islay", "ILY" ],
      [ "Inisheer Aerodrome", "INQ" ],
      [ "Inverness", "INV" ],
      [ "Kilronan", "IOR", "AKA Inishmore Aerodrome" ],
      [ "St. Mary's", "ISC" ],
      [ "Kerry County", "KIR" ],
      [ "Kilkenny", "KKY" ],
      [ "Orkney - Kirkwall", "KOI" ],
      [ "Redhill Aerodrome", "KRH" ],
      [ "Leeds Bradford", "LBA" ],
      [ "London - City", "LCY" ],
      [ "Derry (Londonderry)", "LDY" ],
      [ "Land's End", "LEQ" ],
      [ "London - Gatwick", "LGW" ],
      [ "London - Heathrow", "LHR" ],
      [ "RAF Lakenheath", "LKZ" ],
      [ "RAF Lossiemouth", "LMO" ],
      [ "Liverpool John Lennon", "LPL" ],
      [ "Land's End", "LQE" ],
      [ "Sumburgh (Shetland)", "LSI" ],
      [ "London - Luton", "LTN" ],
      [ "Letterkenny", "LTR" ],
      [ "Lerwick / Tingwall (Shetland Islands)", "LWK" ],
      [ "RAF Lyneham", "LYE" ],
      [ "Lydd International", "LYX" ],
      [ "Manchester", "MAN" ],
      [ "RAF Mildenhall", "MHZ" ],
      [ "Durham Tees Valley", "MME" ],
      [ "RAF Marham", "MRH" ],
      [ "Kent (Manston) Kent International", "MSE", "Manston" ],
      [ "Newcastle", "NCL" ],
      [ "Sanday", "NDY" ],
      [ "RAF Northolt", "NHT" ],
      [ "Connemara Regional", "NNR" ],
      [ "Knock", "NOC", "Ireland West Knock" ],
      [ "Nottingham", "NQT" ],
      [ "Newquay", "NQY" ],
      [ "North Ronaldsay", "NRL" ],
      [ "Norwich International", "NWI" ],
      [ "Oban", "OBN" ],
      [ "RAF Odiham", "ODH" ],
      [ "RAF Cottesmore", "OKH" ],
      [ "Cork", "ORK" ],
      [ "Sywell Aerodrome", "ORM" ],
      [ "Out Skerries (Shetland)", "OUK" ],
      [ "Oxford (Kidlington)", "OXF" ],
      [ "Glasgow Prestwick", "PIK" ],
      [ "Plymouth City", "PLH" ],
      [ "Papa Westray", "PPW" ],
      [ "Perth / Scone", "PSL" ],
      [ "Papa Stour", "PSV" ],
      [ "Penzance Heliport", "PZE" ],
      [ "RAF Coningsby", "QCY" ],
      [ "Duxford", "QFO" ],
      [ "Lasham", "QLA" ],
      [ "Chichester / Goodwood", "QUG" ],
      [ "RAF Wyton", "QUY" ],
      [ "Rochester", "RCS" ],
      [ "Scatsta", "SCS" ],
      [ "Southend", "SEN" ],
      [ "Skye Bridge Ashaig", "SKL" ],
      [ "Shannon (Limerick)", "SNN" ],
      [ "Southampton - Eastleigh", "SOU" ],
      [ "Stronsay", "SOY" ],
      [ "RAF Scampton", "SQZ" ],
      [ "London - Stansted", "STN" ],
      [ "Swansea", "SWS" ],
      [ "Sligo", "SXL" ],
      [ "Stornoway", "SYY" ],
      [ "Sheffield City", "SZD" ],
      [ "Sheffield City Heliport", "SZE" ],
      [ "Tiree", "TRE" ],
      [ "Glenforsa Airfield", "ULL" ],
      [ "Unst", "UNT" ],
      [ "Waterford", "WAT" ],
      [ "Castlebridge", "WEX" ],
      [ "Whalsay", "WHS" ],
      [ "Wick", "WIC" ],
      [ "Wick", "WIC" ],
      [ "Westray", "WRY" ],
      [ "RAF Waddington", "WTN" ],
      [ "Wethersfield", "WXF" ],
      [ "Manchester Woodford", "XXB" ],
      [ "RNAS Yeovilton", "YEO" ]
    ],
    "OK, not dates this one but something that does come up in the quiz that we do..."
  ],
  [
    "Periodic table",
    [
      [ "Hydrogen", "H", "Atomic number 1"],
      [ "Helium", "He", "Atomic number 2"],
      [ "Lithium", "Li", "Atomic number 3"],
      [ "Beryllium", "Be", "Atomic number 4"],
      [ "Boron", "B", "Atomic number 5"],
      [ "Carbon", "C", "Atomic number 6"],
      [ "Nitrogen", "N", "Atomic number 7"],
      [ "Oxygen", "O", "Atomic number 8"],
      [ "Fluorine", "F", "Atomic number 9"],
      [ "Neon", "Ne", "Atomic number 10"],
      [ "Sodium", "Na", "Atomic number 11"],
      [ "Magnesium", "Mg", "Atomic number 12"],
      [ "Aluminium", "Al", "Atomic number 13"],
      [ "Silicon", "Si", "Atomic number 14"],
      [ "Phosphorus", "P", "Atomic number 15"],
      [ "Sulfur", "S", "Atomic number 16"],
      [ "Chlorine", "Cl", "Atomic number 17"],
      [ "Argon", "Ar", "Atomic number 18"],
      [ "Potassium", "K", "Atomic number 19"],
      [ "Calcium", "Ca", "Atomic number 20"],
      [ "Scandium", "Sc", "Atomic number 21"],
      [ "Titanium", "Ti", "Atomic number 22"],
      [ "Vanadium", "V", "Atomic number 23"],
      [ "Chromium", "Cr", "Atomic number 24"],
      [ "Manganese", "Mn", "Atomic number 25"],
      [ "Iron", "Fe", "Atomic number 26"],
      [ "Cobalt", "Co", "Atomic number 27"],
      [ "Nickel", "Ni", "Atomic number 28"],
      [ "Copper", "Cu", "Atomic number 29"],
      [ "Zinc", "Zn", "Atomic number 30"],
      [ "Gallium", "Ga", "Atomic number 31"],
      [ "Germanium", "Ge", "Atomic number 32"],
      [ "Arsenic", "As", "Atomic number 33"],
      [ "Selenium", "Se", "Atomic number 34"],
      [ "Bromine", "Br", "Atomic number 35"],
      [ "Krypton", "Kr", "Atomic number 36"],
      [ "Rubidium", "Rb", "Atomic number 37"],
      [ "Strontium", "Sr", "Atomic number 38"],
      [ "Yttrium", "Y", "Atomic number 39"],
      [ "Zirconium", "Zr", "Atomic number 40"],
      [ "Niobium", "Nb", "Atomic number 41"],
      [ "Molybdenum", "Mo", "Atomic number 42"],
      [ "Technetium", "Tc", "Atomic number 43"],
      [ "Ruthenium", "Ru", "Atomic number 44"],
      [ "Rhodium", "Rh", "Atomic number 45"],
      [ "Palladium", "Pd", "Atomic number 46"],
      [ "Silver", "Ag", "Atomic number 47"],
      [ "Cadmium", "Cd", "Atomic number 48"],
      [ "Indium", "In", "Atomic number 49"],
      [ "Tin", "Sn", "Atomic number 50"],
      [ "Antimony", "Sb", "Atomic number 51"],
      [ "Tellurium", "Te", "Atomic number 52"],
      [ "Iodine", "I", "Atomic number 53"],
      [ "Xenon", "Xe", "Atomic number 54"],
      [ "Caesium", "Cs", "Atomic number 55"],
      [ "Barium", "Ba", "Atomic number 56"],
      [ "Lanthanum", "La", "Atomic number 57"],
      [ "Cerium", "Ce", "Atomic number 58"],
      [ "Praseodymium", "Pr", "Atomic number 59"],
      [ "Neodymium", "Nd", "Atomic number 60"],
      [ "Promethium", "Pm", "Atomic number 61"],
      [ "Samarium", "Sm", "Atomic number 62"],
      [ "Europium", "Eu", "Atomic number 63"],
      [ "Gadolinium", "Gd", "Atomic number 64"],
      [ "Terbium", "Tb", "Atomic number 65"],
      [ "Dysprosium", "Dy", "Atomic number 66"],
      [ "Holmium", "Ho", "Atomic number 67"],
      [ "Erbium", "Er", "Atomic number 68"],
      [ "Thulium", "Tm", "Atomic number 69"],
      [ "Ytterbium", "Yb", "Atomic number 70"],
      [ "Lutetium", "Lu", "Atomic number 71"],
      [ "Hafnium", "Hf", "Atomic number 72"],
      [ "Tantalum", "Ta", "Atomic number 73"],
      [ "Tungsten", "W", "Atomic number 74"],
      [ "Rhenium", "Re", "Atomic number 75"],
      [ "Osmium", "Os", "Atomic number 76"],
      [ "Iridium", "Ir", "Atomic number 77"],
      [ "Platinum", "Pt", "Atomic number 78"],
      [ "Gold", "Au", "Atomic number 79"],
      [ "Mercury", "Hg", "Atomic number 80"],
      [ "Thallium", "Tl", "Atomic number 81"],
      [ "Lead", "Pb", "Atomic number 82"],
      [ "Bismuth", "Bi", "Atomic number 83"],
      [ "Polonium", "Po", "Atomic number 84"],
      [ "Astatine", "At", "Atomic number 85"],
      [ "Radon", "Rn", "Atomic number 86"],
      [ "Francium", "Fr", "Atomic number 87"],
      [ "Radium", "Ra", "Atomic number 88"],
      [ "Actinium", "Ac", "Atomic number 89"],
      [ "Thorium", "Th", "Atomic number 90"],
      [ "Protactinium", "Pa", "Atomic number 91"],
      [ "Uranium", "U", "Atomic number 92"],
      [ "Neptunium", "Np", "Atomic number 93"],
      [ "Plutonium", "Pu", "Atomic number 94"],
      [ "Americium", "Am", "Atomic number 95"],
      [ "Curium", "Cm", "Atomic number 96"],
      [ "Berkelium", "Bk", "Atomic number 97"],
      [ "Californium", "Cf", "Atomic number 98"],
      [ "Einsteinium", "Es", "Atomic number 99"],
      [ "Fermium", "Fm", "Atomic number 100"],
      [ "Mendelevium", "Md", "Atomic number 101"],
      [ "Nobelium", "No", "Atomic number 102"],
      [ "Lawrencium", "Lr", "Atomic number 103"],
      [ "Rutherfordium", "Rf", "Atomic number 104"],
      [ "Dubnium", "Db", "Atomic number 105"],
      [ "Seaborgium", "Sg", "Atomic number 106"],
      [ "Bohrium", "Bh", "Atomic number 107"],
      [ "Hassium", "Hs", "Atomic number 108"],
      [ "Meitnerium", "Mt", "Atomic number 109"],
      [ "Darmstadtium", "Ds", "Atomic number 110"],
      [ "Roentgenium", "Rg", "Atomic number 111"],
      [ "Copernicium", "Cn", "Atomic number 112"],
      [ "Ununtrium", "Uut", "Atomic number 113"],
      [ "Ununquadium", "Uuq", "Atomic number 114"],
      [ "Ununpentium", "Uup", "Atomic number 115"],
      [ "Ununhexium", "Uuh", "Atomic number 116"],
      [ "Ununseptium", "Uus", "Atomic number 117"],
      [ "Ununoctium", "Uuo", "Atomic number 118"],
    ],
    "Again not dates, maybe I should change the name of this quiz..?"
  ],
  [
    "English monarchs",
    [
      [ "Offa", 774, 796 ],
      [ "Egbert", 802, 839 ],
      [ "Aethelwulf", 839, 856 ],
      [ "Aethelbald", 856, 860 ],
      [ "Aethelberht", 860, 865 ],
      [ "Aethelred", 865, 871 ],
      [ "Alfred the Great", 871, 899 ],
      [ "Edward the Elder", 899, 924 ],
      [ "Aethelstan the Glorious", 924, 939 ],
      [ "Edmund the Magnificent", 939, 946 ],
      [ "Eadred", 946, 955 ],
      [ "Eadwig", 955, 959 ],
      [ "Edgar the Peaceful", 959, 975 ],
      [ "Saint Edward the Martyr", 975, 978 ],
      [ "Aethelred the Unready", 978, 1013 ],
      [ "Sweyn Forkbeard", 1013, 1014 ],
      [ "Aethelred the Ill-Advised", 1014, 1016, "Aethelred the Unready's second reign" ],
      [ "Edmund Ironside", 1016, 1016 ],
      [ "Cnut", 1016, 1035 ],
      [ "Harold Harefoot", 1035, 1040 ],
      [ "Harthacnut", 1040, 1042 ],
      [ "Saint Edward the Confesssor", "1042-06-09", "1066-01-05" ],
      [ "Harold Godwinson", "1066-01-06", "1066-10-14" ],
      // [ "Edgar the Aetheling", "1066-10-15", "1066-12-17", "Proclaimed but never crowned" ],
      [ "William I", "1066-12-25", "1087-09-25" ],
      [ "William II", "1087-09-26", "1100-08-04" ],
      [ "Henry I", "1100-08-05", "1135-12-21" ],
      [ "Stephen", "1135-12-22", "1154-12-18" ],
      [ "Henry II", "1154-12-19", "1170-06-13" ],
      // [ "Henry the Young King", "1170", "1183" ],
      [ "Richard I", "1189-09-03", "1199-05-26", "Richard the Lion Heart" ],
      [ "John", "1199-05-27", "1216-10-27" ],
      [ "Henry III", "1216-10-28", "1272-11-19" ],
      [ "Edward I", "1272-11-20", "1307-07-06", "Longshanks" ],
      [ "Edward II", "1307-07-07", "1327-01-24" ],
      [ "Edward III", "1327-01-25", "1377-06-20" ],
      [ "Richard II", "1377-06-21", "1399-09-29" ],
      [ "Henry IV", "1399-09-30", "1413-03-19" ],
      [ "Henry V", "1413-03-20", "1422-08-30" ],
      [ "Henry VI", "1422-08-31", "1461-03-04" ],
    ],
    "From http://en.wikipedia.org/wiki/List_of_English_monarchs"
  ],
  [
    'US state capitals',
    [
       [ "Alabama", "Montgomery", "Birmingham, Alabama" ],
       [ "Alaska", "Juneau", "Juneau is the largest capital by land area. Anchorage, Alaska" ],
       [ "Arizona", "Phoenix", "Phoenix is the most populous U.S. state capital." ],
       [ "Arkansas", "Little Rock" ],
       [ "California", "Sacramento", "The Supreme Court of California sits in San Francisco. Los Angeles is the state's largest city." ],
       [ "Colorado", "Denver" ],
       [ "Connecticut", "Hartford", "Bridgeport, Connecticut" ],
       [ "Delaware", "Dover", "Longest-serving capital in terms of statehood.  Wilmington, Delaware" ],
       [ "Florida", "Tallahassee", "Jacksonville, Florida" ],
       [ "Georgia (U.S. state)", "Atlanta" ],
       [ "Hawaii", "Honolulu" ],
       [ "Idaho", "Boise" ],
       [ "Illinois", "Springfield", "Springfield is the smallest state capital with population above 100,000 (on List of united states cities by population" ],
       [ "Indiana", "Indianapolis" ],
       [ "Iowa", "Des Moines" ],
       [ "Kansas", "Topeka", "Wichita, Kansas" ],
       [ "Kentucky", "Frankfort", "Louisville, Kentucky" ],
       [ "Louisiana", "Baton Rouge", "New Orleans is the state's largest city and home to the Louisiana Supreme Court." ],
       [ "Maine", "Augusta", "Augusta was officially made the capital 1827, but the legislature did not sit there until 1832. Portland, Maine" ],
       [ "Maryland", "Annapolis", "Annapolis is the third-longest serving capital in the United States after Santa Fe and Boston. Its capitol building is the oldest still in use. It is also the smallest capital by land area. Baltimore is the state's largest city." ],
       [ "Massachusetts", "Boston", "Boston is the longest continuously serving capital in the United States. The Boston-Worcester-Manchester Combined Statistical Area encompasses the state capitals of Massachusetts, New Hampshire, and Rhode Island." ],
       [ "Michigan", "Lansing", "Lansing is the only state capital that is not also the county seat of the county in which it is situated. Detroit is the state's largest city." ],
       [ "Minnesota", "Saint Paul", "Minneapolis is the state's largest city; it and Saint Paul form the core of Minneapolis – Saint Paul" ],
       [ "Mississippi", "Jackson" ],
       [ "Missouri", "Jefferson City", "Kansas City, Missouri" ],
       [ "Montana", "Helena", "Billings, Montana" ],
       [ "Nebraska", "Lincoln", "Omaha, Nebraska" ],
       [ "Nevada", "Carson City", "Las Vegas, Nevada" ],
       [ "New Hampshire", "Concord", "Manchester, New Hampshire" ],
       [ "New Jersey", "Trenton", "Newark, New Jersey" ],
       [ "New Mexico", "Santa Fe", "Santa Fe is the longest serving capital in the United States." ],
       [ "New York", "Albany", "Albany is the largest U.S. state capital with population under 100,000 (and therefore not on List of united states cities by population." ],
       [ "North Carolina", "Raleigh", "Charlotte, North Carolina." ],
       [ "North Dakota", "Bismarck", "Fargo, North Dakota." ],
       [ "Ohio", "Columbus", "Columbus is Ohio's largest city, and the fourth-largest state capital, but the Cincinnati-Northern Kentucky metropolitan area." ],
       [ "Oklahoma", "Oklahoma City", "Oklahoma City is the shortest serving current state capital in the United States.." ],
       [ "Oregon", "Salem", "Portland, Oregon." ],
       [ "Pennsylvania", "Harrisburg", "Philadelphia is the state's largest city.." ],
       [ "Rhode Island", "Providence", "Providence also served as the capital 1636–1686 and 1689–1776. It was one of five co-capitals 1776–1853, and one of two co-capitals 1853–1900.." ],
       [ "South Carolina", "Columbia" ],
       [ "South Dakota", "Pierre", "Sioux Falls, South Dakota." ],
       [ "Tennessee", "Nashville", "Memphis, Tennessee." ],
       [ "Texas", "Austin", "Houston is the state's largest city and the previous capital, and Dallas–Fort Worth Metroplex." ],
       [ "Utah", "Salt Lake City" ],
       [ "Vermont", "Montpelier", "Montpelier is the least populous U.S. state capital. Burlington, Vermont." ],
       [ "Virginia", "Richmond", "Virginia Beach is the state's largest city, and Northern Virginia is the state's largest metro area.." ],
       [ "Washington", "Olympia" ],
       [ "West Virginia", "Charleston" ],
       [ "Wisconsin", "Madison", "Milwaukee is the state's largest city.." ],
       [ "Wyoming", "Cheyenne" ]
    ],
    "From http://en.wikipedia.org/wiki/List_of_capitals_in_the_United_States"
  ]
];
